# Site settings
name: Brittany Chiang
title: Hello World!
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://saurabhkanswal.me
baseurl: ""
email: saurabhkanswal8101@gmail.com
# cover: https://brittanychiang.com/img/og.png
# logo: https://brittanychiang.com/img/emojis/technologist.png
# resume: https://brittanychiang.com/resume.pdf
social:
  - title: email
    url: mailto:saurabhkanswal8101@gmail.com
  - title: twitter
    url: https://twitter.com/kanswal_saurabh
  - title: instagram
    url: https://instagram.com/saurabhkanswal
  - title: codepen
    url: http://codepen.io/saurabhkanswal
  - title: github
    url: https://github.com/saurabhkanswal
  - title: linkedin
    url: https://www.linkedin.com/in/saurabhkanswal

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
