# Site settings
name: shivani kanswal
title: Hello World!
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://shivanikanswal.me
baseurl: ""
email: shivanikanswal@gmail.com
# cover: https://shivanikanswal.me/img/og.png
# logo: https://shivanikanswal/img/emojis/technologist.png
# resume: https://shivanikanswal/resume.pdf
social:
  - title: email
    url: mailto:shivanikanswal@gmail.com
  - title: twitter
    url: https://twitter.com/shivanikanswal
  - title: instagram
    url: https://instagram.com/shivanikanswal
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/shivanikanswal
  - title: linkedin
    url: https://www.linkedin.com/in/shivanikanswal

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
